name             'package_installer'
maintainer       'Chris Roberts'
maintainer_email 'chrisroberts.code@gmail.com'
license          'Apache-2.0'
description      'Installs/Updates system packages'
version          '0.0.1'
